title: Jon Saad-Falcon
tagline: Undergraduate Student at Georgia Tech
url: https://jonsaadfalcon.com
baseurl: ""
# gems: [jekyll-paginate]
# paginate: 5

# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink: "/:title"
# relative_permalinks: true

sass:
  sass_dir: _sass
  style: compressed

author:
  name: Jon Saad-Falcon
  url: https://jonsaadfalcon.com
  email: jonsaadfalcon@gmail.com

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-feed
